apiVersion: v1
kind: Service
metadata:
  name: react-frontend
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: react-frontend
